src/Entity/Weather.php
<?php

namespace App\Entity;

use App\Repository\WeatherRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: WeatherRepository::class)]
class Weather
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'weather')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Place $place = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 3, scale: '0')]
    private ?string $temperature = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 3, scale: '0')]
    private ?string $humiditi = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 3, scale: '0')]
    private ?string $wind_speed = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 4, scale: '0')]
    private ?string $pressure = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 2, scale: '0')]
    private ?string $UV = null;

    #[ORM\Column(length: 255)]
    private ?string $weather_type = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPlace(): ?Place
    {
        return $this->place;
    }

    public function setPlace(?Place $place): static
    {
        $this->place = $place;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getTemperature(): ?string
    {
        return $this->temperature;
    }

    public function getFahrenheit()
    {
        return ($this->temperature * 9/5) + 32;
    }

    public function setTemperature(string $temperature): static
    {
        $this->temperature = $temperature;

        return $this;
    }

    public function getHumiditi(): ?string
    {
        return $this->humiditi;
    }

    public function setHumiditi(string $humiditi): static
    {
        $this->humiditi = $humiditi;

        return $this;
    }

    public function getWindSpeed(): ?string
    {
        return $this->wind_speed;
    }

    public function setWindSpeed(string $wind_speed): static
    {
        $this->wind_speed = $wind_speed;

        return $this;
    }

    public function getPressure(): ?string
    {
        return $this->pressure;
    }

    public function setPressure(string $pressure): static
    {
        $this->pressure = $pressure;

        return $this;
    }

    public function getUV(): ?string
    {
        return $this->UV;
    }

    public function setUV(string $UV): static
    {
        $this->UV = $UV;

        return $this;
    }

    public function getWeatherType(): ?string
    {
        return $this->weather_type;
    }

    public function setWeatherType(string $weather_type): static
    {
        $this->weather_type = $weather_type;

        return $this;
    }
}

src/Controller/WeatherMeasurementController.php
<?php

namespace App\Controller;

use App\Entity\Weather;
use App\Form\WeatherType;
use App\Repository\WeatherRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/measurement')]
class WeatherMeasurementController extends AbstractController
{
    #[Route('/', name: 'app_weather_measurement_index', methods: ['GET'])]
    #[IsGranted('ROLE_MEASUREMENT_INDEX')]
    public function index(WeatherRepository $weatherRepository): Response
    {
        return $this->render('weather_measurement/index.html.twig', [
            'weather' => $weatherRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_weather_measurement_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_MEASUREMENT_NEW')]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $weather = new Weather();
        $form = $this->createForm(WeatherType::class, $weather, [
            'validation_groups' => 'create'
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($weather);
            $entityManager->flush();

            return $this->redirectToRoute('app_weather_measurement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('weather_measurement/new.html.twig', [
            'weather' => $weather,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_weather_measurement_show', methods: ['GET'])]
    #[IsGranted('ROLE_MEASUREMENT_SHOW')]
    public function show(Weather $weather): Response
    {
        return $this->render('weather_measurement/show.html.twig', [
            'weather' => $weather,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_weather_measurement_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_MEASUREMENT_EDIT')]
    public function edit(Request $request, Weather $weather, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(WeatherType::class, $weather, [
            'validation_groups' => 'edit'
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_weather_measurement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('weather_measurement/edit.html.twig', [
            'weather' => $weather,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_weather_measurement_delete', methods: ['POST'])]
    #[IsGranted('ROLE_MEASUREMENT_DELETE')]
    public function delete(Request $request, Weather $weather, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$weather->getId(), $request->request->get('_token'))) {
            $entityManager->remove($weather);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_weather_measurement_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/weather_measurement/_delete_form.html.twig
<form method="post" action="{{ path('app_weather_measurement_delete', {'id': weather.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ weather.id) }}">
    <button class="btn">Delete</button>
</form>

templates/weather_measurement/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/weather_measurement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Weather{% endblock %}

{% block body %}
    <h1>Edit Weather</h1>

    {{ include('weather_measurement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_weather_measurement_index') }}">back to list</a>

    {{ include('weather_measurement/_delete_form.html.twig') }}
{% endblock %}

templates/weather_measurement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Weather index{% endblock %}

{% block body %}
    <h1>Weather index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Temperature</th>
                <th>Humiditi</th>
                <th>Wind_speed</th>
                <th>Pressure</th>
                <th>UV</th>
                <th>Weather_type</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for weather in weather %}
            <tr>
                <td>{{ weather.id }}</td>
                <td>{{ weather.date ? weather.date|date('Y-m-d') : '' }}</td>
                <td>{{ weather.temperature }}</td>
                <td>{{ weather.humiditi }}</td>
                <td>{{ weather.windSpeed }}</td>
                <td>{{ weather.pressure }}</td>
                <td>{{ weather.UV }}</td>
                <td>{{ weather.weatherType }}</td>
                <td>
                    {% if is_granted('ROLE_MEASUREMENT_SHOW') %}
                        <a href="{{ path('app_weather_measurement_show', {'id': weather.id}) }}">show</a>
                    {% endif %}
                    {% if is_granted('ROLE_MEASUREMENT_EDIT') %}
                        <a href="{{ path('app_weather_measurement_edit', {'id': weather.id}) }}">edit</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_granted('ROLE_MEASUREMENT_NEW') %}
        <a href="{{ path('app_weather_measurement_new') }}">Create new</a>
    {% endif %}
{% endblock %}

templates/weather_measurement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Weather{% endblock %}

{% block body %}
    <h1>Create new Weather</h1>

    {{ include('weather_measurement/_form.html.twig') }}

    <a href="{{ path('app_weather_measurement_index') }}">back to list</a>
{% endblock %}

templates/weather_measurement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Weather{% endblock %}

{% block body %}
    <h1>Weather</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ weather.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ weather.date ? weather.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Temperature</th>
                <td>{{ weather.temperature }}</td>
            </tr>
            <tr>
                <th>Humiditi</th>
                <td>{{ weather.humiditi }}</td>
            </tr>
            <tr>
                <th>Wind_speed</th>
                <td>{{ weather.windSpeed }}</td>
            </tr>
            <tr>
                <th>Pressure</th>
                <td>{{ weather.pressure }}</td>
            </tr>
            <tr>
                <th>UV</th>
                <td>{{ weather.UV }}</td>
            </tr>
            <tr>
                <th>Weather_type</th>
                <td>{{ weather.weatherType }}</td>
            </tr>
        </tbody>
    </table>

    {% if is_granted('ROLE_MEASUREMENT_INDEX') %}
        <a href="{{ path('app_weather_measurement_index') }}">back to list</a>
    {% endif %}
    {% if is_granted('ROLE_MEASUREMENT_EDIT') %}
        <a href="{{ path('app_weather_measurement_edit', {'id': weather.id}) }}">edit</a>
    {% endif %}
    {% if is_granted('ROLE_MEASUREMENT_DELETE') %}
        {{ include('weather_measurement/_delete_form.html.twig') }}
    {% endif %}
{% endblock %}