src/Entity/Place.php
<?php

namespace App\Entity;

use App\Repository\PlaceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlaceRepository::class)]
class Place
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 2)]
    private ?string $country_code = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 7)]
    private ?string $x_axis = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 7)]
    private ?string $y_axis = null;

    #[ORM\OneToMany(mappedBy: 'place', targetEntity: Weather::class)]
    private Collection $weather;

    public function __construct()
    {
        $this->weather = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getCountryCode(): ?string
    {
        return $this->country_code;
    }

    public function setCountryCode(string $country_code): static
    {
        $this->country_code = $country_code;

        return $this;
    }

    public function getXAxis(): ?string
    {
        return $this->x_axis;
    }

    public function setXAxis(string $x_axis): static
    {
        $this->x_axis = $x_axis;

        return $this;
    }

    public function getYAxis(): ?string
    {
        return $this->y_axis;
    }

    public function setYAxis(string $y_axis): static
    {
        $this->y_axis = $y_axis;

        return $this;
    }

    /**
     * @return Collection<int, Weather>
     */
    public function getWeather(): Collection
    {
        return $this->weather;
    }

    public function addWeather(Weather $weather): static
    {
        if (!$this->weather->contains($weather)) {
            $this->weather->add($weather);
            $weather->setPlace($this);
        }

        return $this;
    }

    public function removeWeather(Weather $weather): static
    {
        if ($this->weather->removeElement($weather)) {
            // set the owning side to null (unless already changed)
            if ($weather->getPlace() === $this) {
                $weather->setPlace(null);
            }
        }

        return $this;
    }
}

src/Form/PlaceType.php
<?php

namespace App\Form;

use App\Entity\Place;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PlaceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('city', null, [
                'attr' => [
                    'placeholder' => "City name"
                ]
            ])
            ->add('country_code', ChoiceType::class, [
                'choices' => [
                    'Poland' => 'pl',
                    'Germany' => 'de',
                    'France' => 'fr',
                    'Spain' => 'es',
                    'Italy' => 'it',
                    'United Kingdom' => 'gb',
                    'United States' => 'us'
                ]
            ])
            ->add('x_axis', NumberType::class)
            ->add('y_axis', NumberType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Place::class,
        ]);
    }
}

src/Controller/PlaceController.php
<?php

namespace App\Controller;

use App\Entity\Place;
use App\Form\PlaceType;
use App\Repository\PlaceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/place')]
class PlaceController extends AbstractController
{
    #[Route('/', name: 'app_place_index', methods: ['GET'])]
    //#[IsGranted('ROLE_PLACE_INDEX')]
    public function index(PlaceRepository $placeRepository): Response
    {
        return $this->render('place/index.html.twig', [
            'places' => $placeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_place_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_PLACE_NEW')]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $place = new Place();
        $form = $this->createForm(PlaceType::class, $place, [
            'validation_groups' => 'create'
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($place);
            $entityManager->flush();

            return $this->redirectToRoute('app_place_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('place/new.html.twig', [
            'place' => $place,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_place_show', methods: ['GET'])]
    #[IsGranted('ROLE_PLACE_SHOW')]
    public function show(Place $place): Response
    {
        return $this->render('place/show.html.twig', [
            'place' => $place,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_place_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_PLACE_EDIT')]
    public function edit(Request $request, Place $place, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PlaceType::class, $place, [
            'validation_groups' => 'edit'
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_place_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('place/edit.html.twig', [
            'place' => $place,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_place_delete', methods: ['POST'])]
    #[IsGranted('ROLE_PLACE_DELETE')]
    public function delete(Request $request, Place $place, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$place->getId(), $request->request->get('_token'))) {
            $entityManager->remove($place);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_place_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/place/_delete_form.html.twig
<form method="post" action="{{ path('app_place_delete', {'id': place.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ place.id) }}">
    <button class="btn">Delete</button>
</form>

templates/place/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/place/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Place{% endblock %}

{% block body %}
    <h1>Edit Place</h1>

    {{ include('place/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_place_index') }}">back to list</a>

    {{ include('place/_delete_form.html.twig') }}
{% endblock %}

templates/place/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Place index{% endblock %}

{% block body %}
    <h1>Place index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>City</th>
                <th>Country_code</th>
                <th>X_axis</th>
                <th>Y_axis</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for place in places %}
            <tr>
                <td>{{ place.id }}</td>
                <td>{{ place.city }}</td>
                <td>{{ place.countryCode }}</td>
                <td>{{ place.xAxis }}</td>
                <td>{{ place.yAxis }}</td>
                <td>
                    {% if is_granted('ROLE_PLACE_SHOW') %}
                        <a href="{{ path('app_place_show', {'id': place.id}) }}">show</a>
                    {% endif %}
                    {% if is_granted('ROLE_PLACE_EDIT') %}
                        <a href="{{ path('app_place_edit', {'id': place.id}) }}">edit</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_granted('ROLE_PLACE_NEW') %}
        <a href="{{ path('app_place_new') }}">Create new</a>
    {% endif %}
{% endblock %}

templates/place/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Place{% endblock %}

{% block body %}
    <h1>Create new Place</h1>

    {{ include('place/_form.html.twig') }}

    <a href="{{ path('app_place_index') }}">back to list</a>
{% endblock %}

templates/place/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Place{% endblock %}

{% block body %}
    <h1>Place</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ place.id }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ place.city }}</td>
            </tr>
            <tr>
                <th>Country_code</th>
                <td>{{ place.countryCode }}</td>
            </tr>
            <tr>
                <th>X_axis</th>
                <td>{{ place.xAxis }}</td>
            </tr>
            <tr>
                <th>Y_axis</th>
                <td>{{ place.yAxis }}</td>
            </tr>
        </tbody>
    </table>
    {% if is_granted('ROLE_PLACE_INDEX') %}
        <a href="{{ path('app_place_index') }}">back to list</a>
    {% endif %}
    {% if is_granted('ROLE_PLACE_EDIT') %}
        <a href="{{ path('app_place_edit', {'id': place.id}) }}">edit</a>
    {% endif %}
    {% if is_granted('ROLE_PLACE_DELETE') %}
        {{ include('place/_delete_form.html.twig') }}
    {% endif %}
{% endblock %}